### ISSUE TITLE
Document the output format

### ISSUE THREAD

**Issue by tomchristie** [jpadilla/django-rest-framework-yaml#1]
Probably be worthwhile to include an example of the yaml output in the index.md and README.md

**Comment by tomchristie** [comment]
Yes that format is correct... http://pyyaml.org/wiki/PyYAMLDocumentation#Dictionarieswithoutnestedcollectionsarenotdumpedcorrectly

Although it's likely that `default_flow_style=False` would be a nicer default. (Tho if that change *does* get made then let's make sure to highlight it as a difference when we release 3.1, and ensure it's easy enough to change by subclassing `YAMLRenderer`)

**Comment by jpadilla** [comment]
@tomchristie yeah I'm setting `default_flow_style=False` to be the default behavior for the renderer.

**Comment by jpadilla** [comment]
@tomchristie how about adding `default_flow_style` as a property on `YAMLRenderer` so if someone wanted the old behavior they'd just do:

```python
class UglyYAMLRenderer(YAMLRenderer):
    default_flow_style = True
```

**Comment by tomchristie** [comment]
Yup that'd be fine. We can then document that in the 'use `django-rest-framework-yaml` now section of the 3.1 release notes.

**Comment by tomchristie** [comment]
Great! Although note the build failures due to the style change.

**Comment by jpadilla** [comment]
@tomchristie already took care of those, updated docs, and release v1.0.2

**Comment by tomchristie** [comment]
Rockin'
