### ISSUE TITLE
django 3 support

### ISSUE THREAD

**Issue by jobec** [jpadilla/django-rest-framework-yaml#9]
When using this module in combination with django 3, the import `from django.utils import six` fails.

Same issue as https://github.com/jpadilla/django-rest-framework-xml/issues/45

**Comment by patvdleer** [comment]
@jpadilla could you apply the same fix here?

**Comment by jpadilla** [comment]
@patvdleer might get to it soon-ish. Would you want to take a stab at basically doing what i did in https://github.com/jpadilla/django-rest-framework-xml/pull/53 here too?

**Comment by patvdleer** [comment]
I did do a quick and dirty fix https://github.com/jpadilla/django-rest-framework-yaml/pull/13 but @SnijderC 's https://github.com/jpadilla/django-rest-framework-yaml/pull/12 may be better, please review both.

**Comment by jpadilla** [comment]
just released v2
